version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: my-static-site
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/html:/usr/share/nginx/html
      - ./src/css:/usr/share/nginx/html/css
      - ./src/js:/usr/share/nginx/html/js
      - ./src/images:/usr/share/nginx/html/images
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/ssl:/etc/nginx/ssl
